{
  "hash": "93abeac69992b662ffdb689a0da599b4",
  "result": {
    "engine": "knitr",
    "markdown": "# 투자분석 과제2 {.unnumbered}\n\n## Problems\n![](images/investment_hw2.png)\n\n## Answer\n\n***(a)***\n\n저는 ***CME group(CME), ICE(ICE), Nasdaq(NDAQ)*** 세가지 종목을 선정하였습니다.\n\n선정 배경으로는,\n\n(1) 제가 거래소 산업에 관심이 많고,\n(2) 세 주식 모두 미국에 상장되어있는 대표적인 글로벌 거래소이며,\n(3) 동일한 거래소 산업이고 S&P500지수의 구성종목이라 동일 선상에서 비교하기 적합할 것으로 보이기 때문입니다.\n\n세 주식의 일별수정주가(Adj. close), 벤치마크지수인 S&P500지수의 일별수정가격, 무위험이자율로 채택한 미연준의 일별 Effective-FFR(Federel Funds Rate)를 활용하였습니다.\n\n    기간 : 직전 10년(2014.4 ~ 2024.3)\n    출처 : [Yahoo Finance](https://finance.yahoo.com/)\n    산출방법 :\n        (월수익률) 지난달 말 대비 월말 가격의 로그수익률\n        (월초과수익률) 월수익률 - 월말 continuous conpounding FFR/12\n        (월분산) 월/월초과수익률의 표본표준편차\n        (평균수익률) 월/월초과수익률을 산술평균하여 연환산 (x12)\n        (평균분산) 월분산을 산술평균하여 연환산 (x12)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n# stocks and market index S&P500 from yahoo finance\ncme <- read_csv(\"investment_hw/cme.csv\") %>% tibble()\nndaq <- read_csv(\"investment_hw/ndaq.csv\") %>% tibble()\nice <- read_csv(\"investment_hw/ice.csv\") %>% tibble()\nspx <- read_csv(\"investment_hw/spx.csv\") %>% tibble()\n# risk-free rate is effective-FFR(federal funds rate)\nffr <- read_csv(\"investment_hw/fedfunds.csv\") %>% tibble()\n# set period 10years\nstrt_dd='20140101'; end_dd='20240331'\n```\n:::\n\n\n\n***(b)***\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# tidy data\nraw_data <- tibble()\nraw_data <- cme %>% mutate(cme=`Adj Close`) %>% select(Date,cme) %>% \n  left_join(ndaq %>% mutate(ndaq=`Adj Close`) %>% select(Date,ndaq)) %>% \n  left_join(ice %>% mutate(ice=`Adj Close`) %>% select(Date,ice)) %>% \n  left_join(spx %>% mutate(spx=`Adj Close`) %>% select(Date,spx)) %>% \n  mutate(day=gsub(\"-\",\"\",Date)) %>% \n  mutate(year=substr(day,1,4)) %>% \n  mutate(month=substr(day,1,6)) %>% \n  filter(day>=strt_dd,day<=end_dd) %>% \n  left_join(ffr %>% \n              mutate(ffr=FEDFUNDS,\n                     month=substr(gsub(\"-\",\"\",as.character(DATE)),1,6)) %>% \n              select(month,ffr)) %>% \n  select(year,month,day,cme,ndaq,ice,spx,ffr,Date)\n# using monthly log return and continuous compound rate\nraw_data <- raw_data %>% \n  mutate(ffr=log((1+ffr/100)))\n\nmonthly_raw <- tibble()\nmonthly_raw <- raw_data %>% \n  group_by(year,month) %>% \n  arrange(day %>% desc()) %>% \n  slice(1) %>% \n  pivot_longer(.,c(\"cme\",\"ndaq\",\"ice\",\"spx\"),\n               names_to = \"name\",values_to = \"price\") %>% \n  ungroup() %>% \n  arrange(name,year,month) %>% \n  mutate(return=log(price)-log(lag(price))) %>%  # monthly log return\n  mutate(excess_return=return-ffr*(1/12)) %>% \n  filter(as.integer(month)>=201404)\n\n# calculate arithmatic mean&var and var-cov matrix of excess return of stocks\nmonthly_stat <- tibble()\nmonthly_stat <- monthly_raw %>% \n  ungroup() %>% \n  group_by(name) %>% \n  summarise(avg_excess=mean(excess_return)*12,\n            var_excess=sd(excess_return)^2*12,\n            avg_return=mean(return)*12,\n            var_return=sd(return)^2*12,\n            avg_rf=mean(ffr)) # Annualized\n# Cov matrix\nvariance_matrix <- monthly_raw %>% \n  ungroup() %>%\n  select(month,name,excess_return) %>% \n  pivot_wider(names_from = \"name\", values_from = \"excess_return\") %>% \n  select(cme,ice,ndaq,spx) %>% \n  var()\n# Corr matrix\ncor_matrix <- monthly_raw %>% \n  ungroup() %>%\n  select(month,name,excess_return) %>% \n  pivot_wider(names_from = \"name\", values_from = \"excess_return\") %>% \n  select(cme,ice,ndaq,spx) %>% \n  cor()\n```\n:::\n\n\n\n위 방법을 기준으로 산출한 각 주식의 평균초과수익률(연환산) 및 공분산행렬은 아래와 같습니다.\n\n**CME 13.3%, ICE 12.4%, Nasdaq 16.6%**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonthly_stat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 x 6\n  name  avg_excess var_excess avg_return var_return avg_rf\n  <chr>      <dbl>      <dbl>      <dbl>      <dbl>  <dbl>\n1 cme       0.133      0.0332      0.147     0.0332 0.0139\n2 ice       0.124      0.0402      0.137     0.0403 0.0139\n3 ndaq      0.166      0.0410      0.180     0.0408 0.0139\n4 spx       0.0893     0.0230      0.103     0.0230 0.0139\n```\n\n\n:::\n:::\n\n\n\n**Variance-Covariance Matrix of three stocks&Benchmark index**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvariance_matrix\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              cme         ice        ndaq          spx\ncme  0.0027651960 0.001728669 0.001145571 0.0008280002\nice  0.0017286687 0.003352164 0.002121414 0.0016542584\nndaq 0.0011455711 0.002121414 0.003414985 0.0016150778\nspx  0.0008280002 0.001654258 0.001615078 0.0019131261\n```\n\n\n:::\n:::\n\n\n\n**Correlation Matrix of three stocks&Benchmark index**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor_matrix\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           cme       ice      ndaq       spx\ncme  1.0000000 0.5677880 0.3727903 0.3599944\nice  0.5677880 1.0000000 0.6270012 0.6532342\nndaq 0.3727903 0.6270012 1.0000000 0.6318693\nspx  0.3599944 0.6532342 0.6318693 1.0000000\n```\n\n\n:::\n:::\n\n\n\n***(c)***\n\n각 주식의 기대수익률과 미래변동성이 과거실현값과 동일하다고 가정하겠습니다.\n\n공매도는 없다고 가정하였으므로 각 주식의 비중이 양수가 되도록 설정하고, 먼저 두개의 주식으로 구성된 포트폴리오의 efficient frontier를 각각 구하도록 하겠습니다.\n\n그런다음, 각 \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Portfolio return/vol of variance combinations three stocks\nportfolio <- tibble()\nportfolio <- tibble(cme=seq(0,0.5,0.001),ice=seq(0,0.5,0.001),ndaq=seq(1,0,-0.002)) %>% \n  union_all(.,tibble(cme=seq(0,0.5,0.001),ice=seq(0,0.3,0.0006),ndaq=seq(1,0.2,-0.0016))) %>% \n  union_all(.,tibble(cme=seq(0,0.7,0.001),ice=0.3,ndaq=seq(0.7,0,-0.001))) %>% \n  union_all(.,tibble(cme=seq(0,1,0.001),ice=seq(1,0,-0.001),ndaq=0)) %>% \n  union_all(.,tibble(cme=seq(0,1,0.001),ice=0,ndaq=seq(1,0,-0.001))) %>% \n  union_all(.,tibble(cme=0,ice=seq(1,0,-0.001),ndaq=seq(0,1,0.001))) %>% \n  mutate(return=cme*monthly_stat$avg_return[1]\n         +ice*monthly_stat$avg_return[2]\n         +ndaq*monthly_stat$avg_return[3],\n         vol=sqrt(cme^2*monthly_stat$var_return[1]\n                  +ice^2*monthly_stat$var_return[2]\n                  +ndaq^2*monthly_stat$var_return[3]\n                  +2*cme*ice*variance_matrix[2]\n                  +2*cme*ndaq*variance_matrix[3]\n                  +2*ndaq*ice*variance_matrix[7])) %>% \n  mutate(sharpe=(return-monthly_stat$avg_rf[1])/vol)\n\nplot_portfolio <- ggplot(data=portfolio,mapping=aes(x=vol,y=return))+\n  geom_point(data=portfolio %>% filter(ndaq==0),size=0.5,color=\"red\")+\n  geom_point(data=portfolio %>% filter(ice==0),size=0.5,color=\"blue\")+\n  geom_point(data=portfolio %>% filter(cme==0),size=0.5,color=\"green\")+\n  scale_x_continuous(limits=c(0.08,0.22))+\n  scale_y_continuous(limits=c(0.13,0.2))+\n  labs(title = \"Invest Opportunity of three stocks\",x=\"standard deviation\",y=\"expected return\") +\n  annotate(geom=\"text\",x=0.18,y=0.155,label=\"CME\")+\n  annotate(geom=\"text\",x=0.205,y=0.184,label=\"Nasdaq\")+\n  annotate(geom=\"text\",x=0.2,y=0.142,label=\"ICE\")+\n  theme_bw()\n\nplot_combination <- plot_portfolio +\n  geom_point(data=portfolio %>% filter(cme!=0&ice!=0&ndaq!=0&ice!=0.3),size=0.5,color=\"black\",alpha=0.3)\n\nplot_combination\n```\n\n::: {.cell-output-display}\n![](investment_hw2_files/figure-pdf/unnamed-chunk-6-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n***(d)***\n\nTangent p/f는 Sharpe r/o를 최대화시키는 세 주식의 조합으로, 위에서 도식화한 투자기회에 대하여 무위험이자율을 y절편으로 가지는 접선을 그려서 시각화할 수 있습니다.\n\n접선의 기울기는 포트폴리오의 초과수익률을 변동성으로 나눈 값으로 Sharpe r/o가 되므로, 이 접선이 CAL에 해당합니다.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharpe=max(portfolio$sharpe)\ntangent <- tibble(vol=seq(0,1,0.01)) %>% \n  mutate(return=monthly_stat$avg_rf[1]+sharpe*vol)\n\nplot_tangent <- plot_combination+\n  geom_line(data=tangent)+\n  annotate(geom=\"text\",x=0.125,y=0.19,label=\"CAL, y=1.2094x+0.0139\")+\n  annotate(geom=\"text\",x=0.125,y=0.183,label=\"sharpe r/o=1.2094\")+\n  annotate(geom=\"text\",x=0.112,y=0.162,label=\"Tangent p/f\")\nplot_tangent\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 95 rows containing missing values or values outside the scale range\n(`geom_line()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](investment_hw2_files/figure-pdf/unnamed-chunk-7-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n이 때, Tangent p/f의 기대수익률/변동성/구성비율은 아래와 같습니다.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nportfolio %>% arrange(sharpe %>% desc()) %>% slice(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 6\n    cme   ice  ndaq return   vol sharpe\n  <dbl> <dbl> <dbl>  <dbl> <dbl>  <dbl>\n1  0.39 0.234 0.376  0.157 0.119   1.21\n```\n\n\n:::\n:::\n\n\n\n***(e)***\n\n만약, 각 주식의 비중이 최소 0.3이 되어야한다면 (d)의 Tangent p/f 구성이 불가능합니다. ICE의 최적비중은 23.4%이기 때문입니다.\n\n따라서, 새로운 최적 포트폴리오는 ICE=0.3으로 고정하고 산출할 수 있으며, 새로운 efficient frontier는 아래와 같습니다.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fix ice=0.3\nportfolio2 <- portfolio %>% filter(ice==0.3)\nsharpe2=max(portfolio2$sharpe)\ntangent2 <- tibble(vol=seq(0,1,0.01)) %>% \n  mutate(return=monthly_stat$avg_rf[1]+sharpe2*vol)\n\n\nplot_tangent2 <- plot_portfolio +\n  geom_point(data=portfolio %>% filter(cme!=0&ndaq!=0&ice==0.3),size=0.5,color=\"black\")+\n  geom_point(data=portfolio %>% filter(cme!=0&ice!=0&ndaq!=0&ice!=0.3),size=0.5,color=\"black\",alpha=0.1)+\n  geom_line(data=tangent2)+\n  annotate(geom=\"text\",x=0.125,y=0.19,label=\"CAL, y=1.2085x+0.0139\")+\n  annotate(geom=\"text\",x=0.125,y=0.183,label=\"sharpe r/o=1.2085\")+\n  annotate(geom=\"text\",x=0.112,y=0.162,label=\"Tangent p/f\")\nplot_tangent2\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 95 rows containing missing values or values outside the scale range\n(`geom_line()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](investment_hw2_files/figure-pdf/unnamed-chunk-9-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n새로운 Tangent p/f의 기대수익률/변동성/구성비율은 아래와 같습니다.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptimal <- portfolio2 %>% arrange(sharpe %>% desc()) %>% slice(1)\noptimal\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 6\n    cme   ice  ndaq return   vol sharpe\n  <dbl> <dbl> <dbl>  <dbl> <dbl>  <dbl>\n1 0.344   0.3 0.356  0.156 0.118   1.21\n```\n\n\n:::\n:::\n\n\n\n***(f)***\n\n먼저, 포트폴리오의 로그수익률이 정규분포를 따른다면 표준정규분포표를 참조하여 Value at Risk를 다음과 같이 산출할 수 있습니다.\n\n$$5\\%\\;VaR=E(r_p)-1.65\\sigma_p=0.156-1.65\\times 0.118=-3.80\\%$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nVaR=optimal$return-1.65*optimal$vol; VaR\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.03802994\n```\n\n\n:::\n:::\n\n\n\n만약 수익률의 분포가 정규분포가 아니라면, Historical VaR 및 ES(Expected Shortfall)을 산출할 수 있습니다. 이를 데이터의 참조기간인 과거 10년간 최적포트폴리오의 월수익률이 필요합니다.\n\n위의 최적포트폴리오는 **CME 34.4%, ICE 30%, Nasdaq 35.6%로 구성된 포트폴리오**이므로, 거래비용 등을 무시하고 매월말 포트폴리오의 구성비율을 조정한다고 가정하고 포트폴리오의 명목금액을 $P_t$, 각 주식의 $(t,t+1)$ 한달간 로그수익률을 $r_{t,k}$라고 한다면 $(t,t+1)$간 포트폴리오의 수익률 $r_t$는 다음과 같습니다.\n\n$$P_{t+1}=0.344\\times P_t\\times e^{r_{t,cme}}+0.3\\times P_t\\times e^{r_{t,ice}}+0.344\\times P_t\\times e^{r_{t,ndaq}}$$\n\n$$\\Rightarrow 1+r_t=\\frac{P_{t+1}}{P_t}=0.344\\times e^{r_{t,cme}}+0.3\\times e^{r_{t,ice}}+0.344\\times e^{r_{t,ndaq}}$$\n\n이를 적용하면 과거 10년간 최적포트폴리오의 월수익률 120개를 얻을 수 있습니다.\n\n이를 오름차순으로 정렬하면 Historical 5% VaR은 6번째 관측값이며, 5% ES는 6개의 관측값의 평균으로 산출할 수 있습니다. 이는 월수익률 기반 VaR 및 ES이므로 $\\sqrt{12}$를 곱하여 연환산하도록 하겠습니다.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptimal_monthly <- tibble()\noptimal_monthly <- monthly_raw %>% \n  select(month,name,return) %>% \n  pivot_wider(names_from = \"name\", values_from = \"return\") %>% \n  mutate(pf_return=optimal$cme*exp(cme)+optimal$ice*exp(ice)+optimal$ndaq*exp(ndaq)-1) %>% \n  select(month,cme,ice,ndaq,pf_return) %>% \n  arrange(pf_return) %>% \n  slice(1:6)\noptimal_monthly\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 x 5\n  month       cme     ice    ndaq pf_return\n  <chr>     <dbl>   <dbl>   <dbl>     <dbl>\n1 202204 -0.0811  -0.132  -0.124    -0.105 \n2 202002 -0.0880  -0.111  -0.127    -0.103 \n3 202003 -0.136   -0.0961 -0.0723   -0.0960\n4 202209 -0.0942  -0.106  -0.0458   -0.0771\n5 202201  0.00454 -0.0768 -0.159    -0.0728\n6 202205 -0.0982  -0.123  -0.0135   -0.0717\n```\n\n\n:::\n:::\n\n\n\nAnnualized 5% VaR은 -24.84%, ES는 -30.38%입니다. \n\n정규분포 가정 하에 산출한 VaR과 큰 차이가 나는 이유는 지난 22년 Covid-19 팬데믹으로 인해 이례적으로 주가가 월 7% 이상 하락하는 급락장이 지속(Left fat tail)되었는데, 이때의 표본이 Historical VaR 산출을 지배한 반면 정규분포 근사시에는 반영되지 않아 차이가 발생하는 것으로 추정됩니다.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist_VaR <- optimal_monthly$pf_return[6]*sqrt(12)\nhist_ES <- mean(optimal_monthly$pf_return[1:6])*sqrt(12)\npaste(round(hist_VaR,6), round(hist_ES,6) , round(VaR,6), sep=\" / \")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"-0.248389 / -0.303774 / -0.03803\"\n```\n\n\n:::\n:::\n\n\n\n***(g)***\n\n",
    "supporting": [
      "investment_hw2_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}